name: build-push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,16 * * *'
  push:
    paths:
      - 'tests/test_bot.py'

jobs:
  build-push:
    runs-on:
      - self-hosted
      - bnk

    steps:
      - name: Checkout
        uses: actions/checkout@v3
